### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by nghialt** [ridvankaradag/tracli-terminal#8]
Hi, I have just installed recently and encountered this issue.

```
tracli status
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/Users/nghia\tracli'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Workspace.create (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/helpers/Workspace.js:10:8)
    at Workspace.get (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/helpers/Workspace.js:18:19)
    at Database.read (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/helpers/Database.js:9:26)
    at Database.get (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/helpers/Database.js:28:31)
    at Task.all (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/models/Task.js:26:15)
    at Task.active (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/models/Task.js:30:17)
    at Status.run (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/commands/Status.js:11:19)
    at App.start (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/lib/App.js:88:16)
    at Object.<anonymous> (/Users/nghia/.npm-packages/lib/node_modules/tracli-terminal/bin/index.js:28:5)
```

Any idea how to fix this?

**Comment by ridvankaradag** [comment]
Hey @nghialt, 
Thanks for the information. #9 fixes this situation, please update your package.
